[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
description = "A Library for learning the ins and outs of rust"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/Jathn/hello-rust"

[dependencies]
